# Generated by Django 4.2.27 on 2026-04-09 08:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_alter_partner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=255, verbose_name='Arabic Name')),
                ('name_en', models.CharField(max_length=255, verbose_name='English Name')),
                ('commercial_record', models.CharField(max_length=50, unique=True, verbose_name='Commercial Record')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brokers/logos/', verbose_name='Broker Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
            },
        ),
        migrations.CreateModel(
            name='BrokerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('BASIC', 'Basic Plan'), ('PRO', 'Professional Plan'), ('ENTERPRISE', 'Enterprise Plan')], max_length=50, verbose_name='Subscription Plan')),
                ('platform_contract_file', models.FileField(blank=True, null=True, upload_to='platform_contracts/')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active Subscription')),
                ('max_clients', models.IntegerField(default=10, verbose_name='Max Allowed Clients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='brokers.broker')),
            ],
            options={
                'verbose_name': 'Broker Subscription',
                'verbose_name_plural': 'Broker Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='BrokerPartnerContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/broker_partner/')),
                ('is_active', models.BooleanField(default=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount/Commission Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_contracts', to='brokers.broker')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_contracts', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Broker-Partner Contract',
                'verbose_name_plural': 'Broker-Partner Contracts',
                'unique_together': {('broker', 'partner')},
            },
        ),
    ]
