# Generated by Django 5.2.8 on 2026-04-12 12:31

import django.db.models.deletion
import service_requests.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_alter_member_national_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (AR)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='ph-file-text', help_text='Phosphor icon class, e.g. ph-file-text, ph-shield-warning', max_length=50, verbose_name='Phosphor Icon Class')),
                ('fields_schema', models.JSONField(default=list, help_text='JSON array of field definitions. Each field: {"name": "...", "label": "...", "type": "text|textarea|date|number|select|checkbox", "required": true/false, "choices": [{"value":"...", "label":"..."}]}', verbose_name='Fields Schema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Request Type',
                'verbose_name_plural': 'Request Types',
                'ordering': ['display_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Reference')),
                ('submitted_on_behalf', models.BooleanField(default=False, help_text='True if HR submitted this on behalf of a member', verbose_name='Submitted On Behalf')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('RETURNED', 'Returned (Needs More Info)'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('data', models.JSONField(default=dict, help_text='Stores the dynamic field values as key-value pairs', verbose_name='Dynamic Field Data')),
                ('broker_note', models.TextField(blank=True, verbose_name='Broker Note / Resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='members.member', verbose_name='Member')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='service_requests.requesttype', verbose_name='Request Type')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
                'permissions': [('can_submit_service_request', 'Can submit new service request'), ('can_process_service_request', 'Can process/resolve service request as Broker')],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('action', models.CharField(help_text='submit, start_review, return, resolve, reject', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='service_requests.servicerequest')),
            ],
            options={
                'verbose_name': 'Request Status Log',
                'verbose_name_plural': 'Request Status Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=service_requests.models.request_file_upload_path)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service_requests.servicerequest')),
            ],
        ),
    ]
