# Generated by Django 4.2.27 on 2026-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_requesttype_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('RETURNED', 'Returned (Needs More Info)'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('TRANSFERRED_TO_MEDICATIONS', 'Transferred to Medications Dept')], db_index=True, default='DRAFT', max_length=50, verbose_name='Status'),
        ),
    ]
