# Generated by Django 4.2.27 on 2026-05-24 13:16

from django.db import migrations

# الأدوار التي تستطيع تقديم طلبات خدمة
SUBMIT_ROLES = ['SUPER_ADMIN', 'HR_ADMIN', 'HR_STAFF', 'MEMBER']

# الأدوار التي تستطيع معالجة طلبات الخدمة (الوسيط)
PROCESS_ROLES = ['SUPER_ADMIN', 'BROKER_ADMIN', 'BROKER_STAFF']


def assign_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    try:
        perm_submit = Permission.objects.get(
            codename='can_submit_service_request',
            content_type__app_label='service_requests',
        )
        perm_process = Permission.objects.get(
            codename='can_process_service_request',
            content_type__app_label='service_requests',
        )
    except Permission.DoesNotExist:
        return  # الصلاحيات لم تُنشأ بعد

    for role in SUBMIT_ROLES:
        group = Group.objects.filter(name=role).first()
        if group:
            group.permissions.add(perm_submit)

    for role in PROCESS_ROLES:
        group = Group.objects.filter(name=role).first()
        if group:
            group.permissions.add(perm_process)


def remove_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    perms = Permission.objects.filter(
        codename__in=['can_submit_service_request', 'can_process_service_request'],
        content_type__app_label='service_requests',
    )
    for group in Group.objects.filter(name__in=SUBMIT_ROLES + PROCESS_ROLES):
        group.permissions.remove(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_alter_servicerequest_status'),
        ('accounts', '0013_cleanup_stale_groups'),
    ]

    operations = [
        migrations.RunPython(assign_permissions, remove_permissions),
    ]
