# Generated by Django 4.2.27 on 2026-01-23 21:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('networks', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=100, verbose_name='Arabic Name')),
                ('name_en', models.CharField(max_length=100, verbose_name='English Name')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon name (e.g., fa-tooth)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=100, verbose_name='Policy Number')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='policies/contracts/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='clients.client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_policies', to='providers.provider')),
            ],
            options={
                'unique_together': {('client', 'policy_number')},
            },
        ),
        migrations.CreateModel(
            name='PolicyClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Class Name')),
                ('annual_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='General Annual Limit')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_classes', to='networks.network', verbose_name='Linked Network')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='policies.policy')),
            ],
            options={
                'unique_together': {('policy', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0, help_text='E.g., 5000 for Dental', max_digits=10, verbose_name='Benefit Limit (SAR)')),
                ('deductible_percentage', models.IntegerField(default=0, help_text='Percentage user pays specific to this benefit', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Co-Pay %')),
                ('description', models.TextField(blank=True, verbose_name='Coverage Details')),
                ('benefit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.benefittype', verbose_name='Benefit Type')),
                ('policy_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='policies.policyclass')),
            ],
            options={
                'verbose_name': 'Class Benefit Detail',
                'unique_together': {('policy_class', 'benefit_type')},
            },
        ),
    ]
