# Generated by Django 4.2.27 on 2026-01-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('policies', '0002_policy_master_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_policies', to='providers.provider'),
        ),
    ]
