# Generated by Django 4.2.27 on 2026-02-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_policy_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefittype',
            options={'permissions': [('manage_benefit_types', 'Can create/edit benefit types')]},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'permissions': [('manage_policy_structure', 'Can create/edit policies and classes'), ('view_policy_details', 'Can view policy coverage details')]},
        ),
    ]
