# Generated by Django 4.2.27 on 2026-05-28 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_alter_network_options_alter_serviceprovider_options'),
        ('providers', '0002_alter_provider_options'),
        ('brokers', '0001_initial'),
        ('policies', '0004_alter_benefittype_options_alter_policy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_plans', to='brokers.broker')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='providers.provider')),
            ],
            options={
                'ordering': ['provider', 'name'],
                'permissions': [('manage_insurance_plans', 'Can create/edit insurance plan templates')],
                'unique_together': {('broker', 'provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PlanClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Class Name')),
                ('annual_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Default Annual Limit')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_classes', to='networks.network', verbose_name='Default Network')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='policies.insuranceplan')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('plan', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='policyclass',
            name='annual_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to inherit from plan class template.', max_digits=12, null=True, verbose_name='General Annual Limit'),
        ),
        migrations.AlterField(
            model_name='policyclass',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_classes', to='networks.network', verbose_name='Linked Network'),
        ),
        migrations.AddField(
            model_name='policy',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='policies.insuranceplan', verbose_name='Insurance Plan Template'),
        ),
        migrations.AddField(
            model_name='policyclass',
            name='plan_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_classes', to='policies.planclass', verbose_name='Plan Class Template'),
        ),
        migrations.CreateModel(
            name='PlanClassBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Benefit Limit (SAR)')),
                ('deductible_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Co-Pay %')),
                ('description', models.TextField(blank=True, verbose_name='Coverage Details')),
                ('benefit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.benefittype', verbose_name='Benefit Type')),
                ('plan_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='policies.planclass')),
            ],
            options={
                'unique_together': {('plan_class', 'benefit_type')},
            },
        ),
    ]
