# Generated by Django 4.2.27 on 2026-05-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_insurance_plan_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbenefit',
            name='is_excluded',
            field=models.BooleanField(default=False, help_text='If checked, this benefit is excluded from coverage even if inherited from the plan.', verbose_name='Excluded'),
        ),
    ]
