# Generated by Django 4.2.27 on 2026-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_alter_network_options_alter_serviceprovider_options'),
        ('policies', '0006_classbenefit_is_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyclass',
            name='excluded_providers',
            field=models.ManyToManyField(blank=True, help_text="Hospitals to exclude from this class's effective network.", related_name='excluded_in_classes', to='networks.serviceprovider', verbose_name='Excluded Hospitals'),
        ),
        migrations.AddField(
            model_name='policyclass',
            name='extra_providers',
            field=models.ManyToManyField(blank=True, help_text='Additional hospitals beyond the assigned network.', related_name='added_in_classes', to='networks.serviceprovider', verbose_name='Extra Hospitals'),
        ),
    ]
