# Generated by Django 4.2.27 on 2026-08-16 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_sponsornumber'),
        ('policies', '0007_add_provider_overrides_to_policyclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='sponsor_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='clients.sponsornumber', verbose_name='Sponsor Number'),
        ),
    ]
