# Generated by Django 4.2.27 on 2026-01-23 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=255, verbose_name='Arabic Name')),
                ('name_en', models.CharField(max_length=255, verbose_name='English Name')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='License Number')),
                ('claim_email', models.EmailField(blank=True, max_length=254, verbose_name='Claims Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='providers/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insurance Provider',
                'verbose_name_plural': 'Insurance Providers',
                'ordering': ['name_en'],
            },
        ),
    ]
