# Generated by Django 4.2.27 on 2026-02-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name_en'], 'permissions': [('manage_insurance_companies', 'Can create/edit insurance companies')], 'verbose_name': 'Insurance Provider', 'verbose_name_plural': 'Insurance Providers'},
        ),
    ]
