# Generated by Django 4.2.27 on 2026-01-23 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=255, verbose_name='Name (AR)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (EN)')),
                ('partner_type', models.CharField(choices=[('PHARMACY_CHAIN', 'Pharmacy Chain'), ('CHRONIC_CENTER', 'Chronic Care Center'), ('OPTICAL_CHAIN', 'Optical Chain'), ('OTHER', 'Other')], max_length=50, verbose_name='Partner Type')),
                ('commercial_record', models.CharField(max_length=50, unique=True, verbose_name='Commercial Record')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contact Person')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='partners/contracts/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner Company',
                'verbose_name_plural': 'Partner Companies',
            },
        ),
    ]
