# Generated by Django 4.2.27 on 2026-02-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'permissions': [('manage_partners', 'Can create/edit partners'), ('view_partner_contracts', 'Can view/download sensitive contract files')], 'verbose_name': 'Partner Company', 'verbose_name_plural': 'Partner Companies'},
        ),
    ]
