# Generated by Django 4.2.27 on 2026-01-23 21:58

import claims.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Claim Ref')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to HR'), ('HR_REVIEW', 'Under HR Review'), ('RETURN_MISSING_DOCS_HR', 'Returned by HR (Missing Docs)'), ('BROKER_REVIEW', 'Under Broker Review'), ('RETURN_MISSING_DOCS_BROKER', 'Returned by Broker (Missing Docs)'), ('RE_SUBMITTED', 'Re-Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid / Settled')], default='DRAFT', max_length=30, verbose_name='Status')),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (Original Currency)')),
                ('approved_amount_sar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Approved Amount (SAR)')),
                ('is_in_patient', models.BooleanField(default=False, verbose_name='In-Patient (Admission)')),
                ('is_international', models.BooleanField(default=False, verbose_name='Treatment Outside KSA')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection/Return Reason')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
            ],
            options={
                'verbose_name': 'Claim Request',
                'verbose_name_plural': 'Claim Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Currency Code')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Name (AR)')),
                ('name_en', models.CharField(max_length=50, verbose_name='Name (EN)')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Exchange Rate to SAR')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', encrypted_model_fields.fields.EncryptedTextField(verbose_name='Comment Message')),
                ('visibility', models.CharField(choices=[('GENERAL', 'General (User, HR, Broker)'), ('INTERNAL', 'Internal (HR & Broker Only)')], default='GENERAL', max_length=10, verbose_name='Visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='claims.claim')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=claims.models.claim_file_upload_path)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='claims.claim')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='currency',
            field=models.ForeignKey(default='SAR', on_delete=django.db.models.deletion.PROTECT, to='claims.currency'),
        ),
        migrations.AddField(
            model_name='claim',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='members.member'),
        ),
    ]
