# Generated by Django 4.2.27 on 2026-02-01 12:12

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('SUBMITTED_TO_HR', 'Submitted to HR'), ('RETURNED_BY_HR', 'Returned by HR (Missing Docs)'), ('SUBMITTED_TO_BROKER', 'Submitted to Broker'), ('BROKER_PROCESSING', 'Under Broker Processing'), ('RETURNED_BY_BROKER', 'Returned by Broker'), ('SENT_TO_INSURANCE', 'Sent to Insurance Company'), ('INSURANCE_QUERY', 'Insurance Query (Docs Needed)'), ('APPROVED_BY_INSURANCE', 'Approved by Insurance'), ('REJECTED_BY_INSURANCE', 'Rejected by Insurance'), ('PAID', 'Paid / Settled')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
    ]
