# Generated by Django 4.2.27 on 2026-02-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit_claim', 'Can submit new claim'), ('can_approve_hr', 'Can approve claim as HR'), ('can_reject_hr', 'Can return/reject claim as HR'), ('can_process_broker', 'Can process claim as Broker'), ('can_approve_payment', 'Can mark claim as Paid'), ('can_view_all_claims', 'Can view all claims'), ('view_sensitive_medical_data', 'Can view sensitive medical attachments')], 'verbose_name': 'Claim Request', 'verbose_name_plural': 'Claim Requests'},
        ),
        migrations.AlterModelOptions(
            name='claimcomment',
            options={'ordering': ['created_at'], 'permissions': [('view_internal_comments', 'Can view internal comments (Hidden from Member)')]},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
