# Generated by Django 5.2.8 on 2026-02-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claimstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimcomment',
            name='message',
            field=models.TextField(verbose_name='Comment Message'),
        ),
    ]
