# Generated by Django 5.2.8 on 2026-04-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claimcomment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimcomment',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='claimcomment',
            name='visibility',
            field=models.CharField(choices=[('GENERAL', 'General (Visible to Member, HR, Broker, Insurance)'), ('HR_BROKER', 'Internal (HR & Broker Only)'), ('BROKER_INSURANCE', 'Internal (Broker & Insurance Only)'), ('BROKER_ONLY', 'Internal (Broker Only)')], default='GENERAL', max_length=20, verbose_name='Visibility'),
        ),
    ]
