# Generated by Django 4.2.27 on 2026-05-24 18:59

from django.db import migrations

# خريطة الصلاحيات → المجموعات
# كل صلاحية ترتبط بالأدوار التي تملك الحق في تنفيذها
PERMISSION_MAP = {
    'can_submit_claim':       ['SUPER_ADMIN', 'MEMBER', 'HR_ADMIN', 'HR_STAFF'],
    'can_approve_hr':         ['SUPER_ADMIN', 'HR_ADMIN', 'HR_STAFF'],
    'can_reject_hr':          ['SUPER_ADMIN', 'HR_ADMIN', 'HR_STAFF'],
    'can_process_broker':     ['SUPER_ADMIN', 'BROKER_ADMIN', 'BROKER_STAFF'],
    'can_process_insurance':  ['SUPER_ADMIN', 'INSURANCE'],
    'can_approve_payment':    ['SUPER_ADMIN', 'BROKER_ADMIN'],
    'can_view_all_claims':    ['SUPER_ADMIN', 'BROKER_ADMIN', 'BROKER_STAFF'],
    'view_sensitive_medical_data': ['SUPER_ADMIN', 'BROKER_ADMIN'],
}


def assign_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for codename, roles in PERMISSION_MAP.items():
        perm = Permission.objects.filter(
            codename=codename,
            content_type__app_label='claims',
        ).first()
        if not perm:
            continue
        for role in roles:
            group = Group.objects.filter(name=role).first()
            if group:
                group.permissions.add(perm)


def remove_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    all_codenames = list(PERMISSION_MAP.keys())
    perms = Permission.objects.filter(
        codename__in=all_codenames,
        content_type__app_label='claims',
    )
    all_roles = set(r for roles in PERMISSION_MAP.values() for r in roles)
    for group in Group.objects.filter(name__in=all_roles):
        group.permissions.remove(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_add_can_process_insurance_permission'),
        ('accounts', '0013_cleanup_stale_groups'),
    ]

    operations = [
        migrations.RunPython(assign_permissions, remove_permissions),
    ]
