# Generated by Django 4.2.27 on 2026-04-20 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_requests', '0003_alter_servicerequest_status'),
        ('partners', '0002_alter_partner_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationRefill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_number', models.PositiveIntegerField(verbose_name='Cycle Number')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('actual_dispense_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Dispense Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing at Pharmacy'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Medication Refill',
                'verbose_name_plural': 'Medication Refills',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='medications.medicationrefill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_date', models.DateField(verbose_name='Prescription Date')),
                ('interval_months', models.PositiveIntegerField(help_text='e.g., 1 for Monthly, 3 for Quarterly', verbose_name='Dispense Interval (Months)')),
                ('total_duration_months', models.PositiveIntegerField(help_text='Total treatment duration, e.g., 6 or 12', verbose_name='Total Duration (Months)')),
                ('delivery_address_snapshot', models.TextField(verbose_name='Delivery Address Snapshot')),
                ('status', models.CharField(choices=[('PROCESSING', 'Under Processing'), ('ACTIVE', 'Active (Refills Generated)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PROCESSING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_medication_requests', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medication_details', to='service_requests.servicerequest', verbose_name='Original Service Request')),
            ],
            options={
                'verbose_name': 'Medication Request',
                'verbose_name_plural': 'Medication Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicationrefill',
            name='medication_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='medications.medicationrequest'),
        ),
        migrations.AddField(
            model_name='medicationrefill',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.partner', verbose_name='Dispensing Pharmacy'),
        ),
        migrations.CreateModel(
            name='MedicationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Comment Message')),
                ('visibility', models.CharField(choices=[('GENERAL', 'General'), ('INTERNAL', 'Internal (Broker & Pharmacy Only)')], default='GENERAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('medication_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='medications.medicationrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='medicationrefill',
            unique_together={('medication_request', 'cycle_number')},
        ),
    ]
