# Generated by Django 4.2.27 on 2026-04-20 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medications.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_requests', '0003_alter_servicerequest_status'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Medication Comment', 'verbose_name_plural': 'Medication Comments'},
        ),
        migrations.AlterModelOptions(
            name='medicationrequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_transfer_to_medications', 'Can transfer service request to medications'), ('can_view_medication_dashboard', 'Can view medications dashboard'), ('can_schedule_refill', 'Can schedule medication refill'), ('can_approve_refill', 'Can approve medication refill'), ('can_dispense_medication', 'Can dispense medication (Pharmacy)'), ('can_view_refill_alerts', 'Can view refill and prescription alerts')], 'verbose_name': 'Medication Request', 'verbose_name_plural': 'Medication Requests'},
        ),
        migrations.AlterModelOptions(
            name='medicationstatuslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medication Status Log', 'verbose_name_plural': 'Medication Status Logs'},
        ),
        migrations.AddField(
            model_name='medicationrefill',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='medicationrefill',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_refills', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='medicationrefill',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='medicationrefill',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_refills', to=settings.AUTH_USER_MODEL, verbose_name='Scheduled By'),
        ),
        migrations.AddField(
            model_name='medicationrequest',
            name='broker_note',
            field=models.TextField(blank=True, verbose_name='Broker Note'),
        ),
        migrations.AddField(
            model_name='medicationrequest',
            name='prescription_validity_months',
            field=models.PositiveIntegerField(default=6, help_text='Number of months the prescription is valid (default: 6)', verbose_name='Prescription Validity (Months)'),
        ),
        migrations.AddField(
            model_name='medicationrequest',
            name='reference',
            field=models.CharField(db_index=True, default='', editable=False, max_length=20, unique=True, verbose_name='Reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicationstatuslog',
            name='medication_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='medications.medicationrequest'),
        ),
        migrations.AlterField(
            model_name='medicationrefill',
            name='scheduled_date',
            field=models.DateField(db_index=True, verbose_name='Scheduled Date'),
        ),
        migrations.AlterField(
            model_name='medicationrefill',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing at Pharmacy'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='medicationrequest',
            name='delivery_address_snapshot',
            field=models.JSONField(default=dict, help_text='Frozen delivery address at time of transfer', verbose_name='Delivery Address Snapshot'),
        ),
        migrations.AlterField(
            model_name='medicationrequest',
            name='prescription_date',
            field=models.DateField(db_index=True, verbose_name='Prescription Date'),
        ),
        migrations.AlterField(
            model_name='medicationrequest',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Under Processing'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PROCESSING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='medicationstatuslog',
            name='refill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='medications.medicationrefill'),
        ),
        migrations.CreateModel(
            name='MedicationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=medications.models.medication_file_upload_path, verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('medication_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='medications.medicationrequest')),
                ('original_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_copies', to='service_requests.requestattachment', verbose_name='Original Attachment')),
            ],
            options={
                'verbose_name': 'Medication Attachment',
                'verbose_name_plural': 'Medication Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
