# Generated by Django 4.2.27 on 2026-01-23 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=255, verbose_name='Arabic Name')),
                ('name_en', models.CharField(max_length=255, verbose_name='English Name')),
                ('commercial_record', models.CharField(max_length=50, unique=True, verbose_name='Commercial Record')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='clients.client', verbose_name='Parent Company (Holding)')),
            ],
            options={
                'verbose_name': 'Client / Company',
                'verbose_name_plural': 'Clients / Companies',
                'ordering': ['name_en'],
            },
        ),
    ]
