# Generated by Django 4.2.27 on 2026-02-01 11:35

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='services_config',
            field=models.JSONField(blank=True, default=clients.models.default_services_config, help_text='JSON configuration for various services (e.g., claims workflow settings).', verbose_name='Services Configuration'),
        ),
    ]
