# Generated by Django 4.2.27 on 2026-02-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_services_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name_en'], 'permissions': [('manage_clients', 'Can create/edit clients'), ('view_client_dashboard', 'Can view client dashboard statistics')], 'verbose_name': 'Client / Company', 'verbose_name_plural': 'Clients / Companies'},
        ),
    ]
