# Generated by Django 4.2.27 on 2026-04-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('clients', '0003_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='brokers.broker', verbose_name='Broker'),
        ),
    ]
