# Generated by Django 4.2.27 on 2026-08-16 17:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_require_hr_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sponsor_number', models.CharField(max_length=50, verbose_name='Sponsor Number (Establishment ID)')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_numbers', to='clients.client', verbose_name='Holding Group')),
                ('owner_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_sponsor_numbers', to='clients.client', verbose_name='Owner Company')),
            ],
            options={
                'verbose_name': 'Sponsor Number',
                'verbose_name_plural': 'Sponsor Numbers',
                'ordering': ['sponsor_number'],
                'unique_together': {('group', 'sponsor_number')},
            },
        ),
    ]
