# Generated by Django 4.2.27 on 2026-02-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BROKER_ADMIN', 'Broker Admin (Super)'), ('BROKER_STAFF', 'Broker Staff'), ('HR_ADMIN', 'HR Admin'), ('HR_STAFF', 'HR Staff'), ('PHARMACIST', 'Pharmacist'), ('CHRONIC_ADMIN', 'Chronic Disease Admin'), ('CHRONIC_STAFF', 'Chronic Disease Staff'), ('VIEWER', 'Viewer / Auditor'), ('MEMBER', 'Member / Beneficiary')], default='MEMBER', max_length=50, verbose_name='Role'),
        ),
    ]
