# Generated by Django 4.2.27 on 2026-02-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (Owner)'), ('BROKER_ADMIN', 'Broker Admin'), ('BROKER_STAFF', 'Broker Staff'), ('HR_ADMIN', 'HR Admin'), ('HR_STAFF', 'HR Staff'), ('PHARMACIST', 'Pharmacist'), ('CHRONIC_ADMIN', 'Chronic Disease Admin'), ('CHRONIC_STAFF', 'Chronic Disease Staff'), ('VIEWER', 'Viewer / Auditor'), ('MEMBER', 'Member / Beneficiary')], default='MEMBER', max_length=50, verbose_name='Role'),
        ),
    ]
