# Generated by Django 4.2.27 on 2026-02-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_broker_dashboard', 'Can view Broker Dashboard'), ('view_hr_dashboard', 'Can view HR Dashboard'), ('view_partner_dashboard', 'Can view Partner Dashboard'), ('view_member_dashboard', 'Can view Member Dashboard'), ('manage_users', 'Can manage system users')]},
        ),
    ]
