# Generated by Django 5.2.8 on 2026-02-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True, verbose_name='National ID'),
        ),
    ]
