# Generated by Django 4.2.27 on 2026-04-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_national_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_broker_dashboard', 'Can view Broker Dashboard'), ('view_hr_dashboard', 'Can view HR Dashboard'), ('view_partner_dashboard', 'Can view Partner Dashboard'), ('view_member_dashboard', 'Can view Member Dashboard'), ('manage_users', 'Can manage system users'), ('manage_company_staff', 'Can Manage My Staff')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone Number'),
        ),
    ]
