# Generated by Django 4.2.27 on 2026-04-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('accounts', '0009_alter_user_options_alter_user_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='brokers.broker', verbose_name='Related Broker (For Brokers)'),
        ),
    ]
