# Generated by Django 4.2.27 on 2026-05-24 12:49

from django.db import migrations

ROLE_NAMES = [
    'SUPER_ADMIN',
    'BROKER_ADMIN',
    'BROKER_STAFF',
    'HR_ADMIN',
    'HR_STAFF',
    'PHARMACIST',
    'CHRONIC_ADMIN',
    'CHRONIC_STAFF',
    'VIEWER',
    'INSURANCE',
    'MEMBER',
]


def create_role_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for name in ROLE_NAMES:
        Group.objects.get_or_create(name=name)


def delete_role_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=ROLE_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_role_groups, delete_role_groups),
    ]
