# Generated by Django 4.2.27 on 2026-05-24 12:52

from django.db import migrations

# المجموعات التي لا تتوافق مع نظام الأدوار الحالي (أُنشئت يدويًا أو من كود قديم)
STALE_GROUP_NAMES = [
    'Broker Admin',
    'Broker Staff',
    'Medical Team',
    'Partner Chronic',
    'Partner Pharmacist',
    'Viewer',
]

VALID_ROLE_NAMES = [
    'SUPER_ADMIN', 'BROKER_ADMIN', 'BROKER_STAFF',
    'HR_ADMIN', 'HR_STAFF', 'PHARMACIST',
    'CHRONIC_ADMIN', 'CHRONIC_STAFF', 'VIEWER',
    'INSURANCE', 'MEMBER',
]


def cleanup_stale_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    # حذف المجموعات القديمة التي لا تنتمي لنظام الأدوار
    Group.objects.filter(name__in=STALE_GROUP_NAMES).delete()
    # حذف أي مجموعات أخرى لا تنتمي للقائمة الرسمية
    Group.objects.exclude(name__in=VALID_ROLE_NAMES).delete()


def reverse_cleanup(apps, schema_editor):
    pass  # لا يمكن استعادة المجموعات المحذوفة


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_create_role_groups'),
    ]

    operations = [
        migrations.RunPython(cleanup_stale_groups, reverse_cleanup),
    ]
