# Generated by Django 4.2.27 on 2026-05-24 19:24

from django.db import migrations

# خريطة صلاحيات accounts → المجموعات
PERMISSION_MAP = {
    # مدير النظام فقط يرى لوحة الوسيط وهو المسيطر الكامل
    'view_broker_dashboard':  ['SUPER_ADMIN', 'BROKER_ADMIN', 'BROKER_STAFF'],
    'view_hr_dashboard':      ['SUPER_ADMIN', 'HR_ADMIN', 'HR_STAFF', 'INSURANCE'],
    'view_partner_dashboard': ['SUPER_ADMIN', 'PHARMACIST', 'CHRONIC_ADMIN', 'CHRONIC_STAFF'],
    'view_member_dashboard':  ['SUPER_ADMIN', 'MEMBER'],
    # إدارة المستخدمين: SUPER_ADMIN فقط (يُنشئ المديرين لجميع الجهات)
    'manage_users':           ['SUPER_ADMIN'],
    # إدارة موظفي الوسيط: BROKER_ADMIN (يُنشئ BROKER_STAFF فقط)
    'manage_broker_staff':    ['SUPER_ADMIN', 'BROKER_ADMIN'],
    # إدارة موظفي HR: HR_ADMIN (يُنشئ HR_STAFF فقط)
    'manage_company_staff':   ['SUPER_ADMIN', 'HR_ADMIN'],
}


def assign_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for codename, roles in PERMISSION_MAP.items():
        perm = Permission.objects.filter(
            codename=codename,
            content_type__app_label='accounts',
        ).first()
        if not perm:
            continue
        for role in roles:
            group = Group.objects.filter(name=role).first()
            if group:
                group.permissions.add(perm)


def remove_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    perms = Permission.objects.filter(
        codename__in=list(PERMISSION_MAP.keys()),
        content_type__app_label='accounts',
    )
    all_roles = set(r for roles in PERMISSION_MAP.values() for r in roles)
    for group in Group.objects.filter(name__in=all_roles):
        group.permissions.remove(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_manage_broker_staff_permission'),
    ]

    operations = [
        migrations.RunPython(assign_permissions, remove_permissions),
    ]
