# Generated by Django 4.2.27 on 2026-01-23 21:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=255, verbose_name='Name (AR)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (EN)')),
                ('type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('POLYCLINIC', 'Polyclinic'), ('PHARMACY', 'Pharmacy'), ('OPTICAL', 'Optical Shop'), ('LAB', 'Laboratory')], max_length=20, verbose_name='Type')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Medical Service Provider',
                'verbose_name_plural': 'Medical Service Providers',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=100, verbose_name='Network Name (AR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Network Name (EN)')),
                ('hospitals', models.ManyToManyField(blank=True, related_name='networks', to='networks.serviceprovider', verbose_name='Included Hospitals')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Medical Network',
                'verbose_name_plural': 'Medical Networks',
                'unique_together': {('provider', 'name_en')},
            },
        ),
    ]
