# Generated by Django 4.2.27 on 2026-02-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'permissions': [('manage_networks', 'Can create/edit networks')], 'verbose_name': 'Medical Network', 'verbose_name_plural': 'Medical Networks'},
        ),
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'permissions': [('manage_providers', 'Can create/edit providers'), ('bulk_upload_providers', 'Can upload provider lists via Excel')], 'verbose_name': 'Medical Service Provider', 'verbose_name_plural': 'Medical Service Providers'},
        ),
    ]
