# Generated by Django 4.2.27 on 2026-01-23 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('frequency_days', models.IntegerField(choices=[(7, 'Weekly'), (14, 'Every 2 Weeks'), (30, 'Monthly'), (90, 'Every 3 Months')], default=30, verbose_name='Visit Frequency')),
                ('next_visit_due', models.DateField(blank=True, null=True, verbose_name='Next Visit Due Date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Care'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('home_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('home_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('managing_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=100, verbose_name='Disease Name (AR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Disease Name (EN)')),
            ],
        ),
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField(verbose_name='Scheduled Date')),
                ('actual_visit_start', models.DateTimeField(blank=True, null=True)),
                ('actual_visit_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled (Auto)'), ('CONFIRMED', 'Confirmed with Patient'), ('ON_THE_WAY', 'Doctor on the Way'), ('IN_PROGRESS', 'Visit In Progress'), ('COMPLETED', 'Visit Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('doctor_notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Doctor Clinical Notes')),
                ('vital_pressure', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('vital_sugar', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='chronic_care.chroniccase')),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'CHRONIC_STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned Doctor')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('instructions', encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Instructions')),
                ('is_dispensed', models.BooleanField(default=False)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='chronic_care.homevisit')),
            ],
        ),
        migrations.CreateModel(
            name='VisitLabRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200, verbose_name='Test Name')),
                ('status', models.CharField(choices=[('PENDING', 'Sample Taken / Pending Result'), ('UPLOADED', 'Result Uploaded'), ('NOTIFIED', 'Patient Notified')], default='PENDING', max_length=20)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='chronic/labs/%Y/%m/')),
                ('result_summary', encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Result Summary')),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('patient_notified', models.BooleanField(default=False)),
                ('notification_notes', models.TextField(blank=True, help_text='e.g. Called patient at 5 PM')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='chronic_care.homevisit')),
            ],
        ),
        migrations.CreateModel(
            name='ChronicRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medical_report', models.FileField(upload_to='chronic/requests/%Y/%m/')),
                ('status', models.CharField(choices=[('NEW', 'New Request'), ('UNDER_BROKER_REVIEW', 'Under Broker Review'), ('ASSIGNED_TO_PARTNER', 'Assigned to Partner'), ('REJECTED', 'Rejected')], default='NEW', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_partner', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'CHRONIC_CENTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chronic_requests', to='partners.partner')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chronic_care.chronicdisease')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_requests', to='members.member')),
            ],
        ),
        migrations.AddField(
            model_name='chroniccase',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_file', to='chronic_care.chronicrequest'),
        ),
    ]
