# Generated by Django 4.2.27 on 2026-02-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronic_care', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chroniccase',
            options={'permissions': [('manage_chronic_cases', 'Can create/edit chronic cases'), ('suspend_case', 'Can suspend or terminate chronic cases')]},
        ),
        migrations.AlterModelOptions(
            name='chronicdisease',
            options={'permissions': [('manage_disease_list', 'Can manage disease list configuration')]},
        ),
        migrations.AlterModelOptions(
            name='chronicrequest',
            options={'permissions': [('manage_chronic_requests', 'Can create/edit chronic requests'), ('approve_request', 'Can approve/reject chronic requests'), ('assign_partner', 'Can assign partner to chronic requests')]},
        ),
        migrations.AlterModelOptions(
            name='homevisit',
            options={'ordering': ['scheduled_date'], 'permissions': [('manage_home_visits', 'Can create/edit home visits'), ('process_visit', 'Can start/complete home visits'), ('view_sensitive_medical_data', 'Can view encrypted doctor notes')]},
        ),
        migrations.AlterModelOptions(
            name='visitlabrequest',
            options={'permissions': [('upload_lab_result', 'Can upload lab test results')]},
        ),
        migrations.AlterModelOptions(
            name='visitprescription',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
