# Generated by Django 5.2.8 on 2026-02-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronic_care', '0002_alter_chroniccase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homevisit',
            name='doctor_notes',
            field=models.TextField(blank=True, verbose_name='Doctor Clinical Notes'),
        ),
        migrations.AlterField(
            model_name='homevisit',
            name='vital_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='homevisit',
            name='vital_sugar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='visitlabrequest',
            name='result_summary',
            field=models.TextField(blank=True, verbose_name='Result Summary'),
        ),
        migrations.AlterField(
            model_name='visitprescription',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Instructions'),
        ),
    ]
