# Generated by Django 4.2.27 on 2026-01-23 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('national_id', encrypted_model_fields.fields.EncryptedCharField(unique=True, verbose_name='National ID / Iqama')),
                ('national_address', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted Address Details', verbose_name='National Address')),
                ('medical_card_number', models.CharField(max_length=50, unique=True, verbose_name='Medical Card ID')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('relation', models.CharField(choices=[('PRINCIPAL', 'Principal (Employee)'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child (Son/Daughter)'), ('PARENT', 'Parent'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('OTHER', 'Other')], max_length=20, verbose_name='Relationship')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clients.client', verbose_name='Company / Client')),
                ('policy_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='policies.policyclass')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='members.member')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member / Beneficiary',
                'verbose_name_plural': 'Members / Beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Document Title')),
                ('file', models.FileField(upload_to='members/docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
            ],
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['medical_card_number'], name='members_mem_medical_c854f4_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['full_name'], name='members_mem_full_na_3f8d20_idx'),
        ),
    ]
