# Generated by Django 4.2.27 on 2026-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='medical_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Medical Card ID'),
        ),
    ]
