# Generated by Django 4.2.27 on 2026-02-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_medical_card_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': [('view_all_members', 'Can view members of their company'), ('manage_members', 'Can add/edit members'), ('bulk_upload_members', 'Can perform bulk upload')], 'verbose_name': 'Member / Beneficiary', 'verbose_name_plural': 'Members / Beneficiaries'},
        ),
    ]
