# Generated by Django 4.2.27 on 2026-02-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': [('view_all_members', 'Can view members of their company'), ('manage_members', 'Can add/edit members'), ('bulk_upload_members', 'Can perform bulk upload'), ('view_my_family_members', 'Can view their own family members')], 'verbose_name': 'Member / Beneficiary', 'verbose_name_plural': 'Members / Beneficiaries'},
        ),
    ]
