# Generated by Django 5.2.8 on 2026-02-15 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='national_address',
            field=models.TextField(blank=True, verbose_name='National Address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='national_id',
            field=models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='National ID / Iqama'),
        ),
    ]
