# Generated by Django 4.2.27 on 2026-08-16 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_sponsornumber'),
        ('members', '0005_alter_member_national_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sponsor_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='clients.sponsornumber', verbose_name='Sponsor Number'),
        ),
    ]
